"""drop kdf_salt from users

Revision ID: 4387e37388b9
Revises: eb95ffda6e15
Create Date: 2026-06-23 13:58:34.909106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4387e37388b9'
down_revision: Union[str, Sequence[str], None] = 'eb95ffda6e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kdf_salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kdf_salt', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
